# https://newrelic.com/docs/ruby/ruby-agent-configuration

common: &default_settings
  license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  app_name: <%= ENV["NEW_RELIC_APP_NAME"] %>

production:
  <<: *default_settings
